version: '3.7'

services:
  speechotron:
    image: ultreme/speechotron
    restart: on-failure
    environment:
     - VIRTUAL_HOST=speech.camembertaulaitcrew.biz
     - VIRTUAL_PORT=8000
    command: server
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - service-proxy
      - internal

  watchtower:
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: --interval 60 --label-enable

networks:
  service-proxy:
    external: true
  internal: